# Generated by Django 2.2.5 on 2021-11-25 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webinvest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('goal_defined', models.FloatField(default=0.0)),
                ('value_acc', models.FloatField(default=0.0)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webinvest.Priority')),
            ],
        ),
    ]
